### PR TITLE
Temporary fix for crash in focus requester code

### PR DESCRIPTION
**Pull request by ankur2136**
#42 

There are some non-answers to this issue so far. https://stackoverflow.com/a/77250333 
Looks like a platform issue to me.

### CODE REVIEW

**Comment by hbmartin** [comment]
What about wrapping it in try/catch ? That way we can usually get the correct behavior but avoid the crash

**Comment by ankur2136** [comment]
> What about wrapping it in try/catch ? That way we can usually get the correct behavior but avoid the crash

I would say both are hacky solutions till we understand why exactly does this path crash in the second instance. Happy to make the change with try/catch

**Comment by hbmartin** [comment]
My guess it has something to do with the final point in the error you posted in the issue `   3. Are you attempting to request focus during composition? Focus requests should be made in response to some event. Eg Modifier.clickable { focusRequester.requestFocus() }` ... which seems entirely contrary to how we want to use it?

I think @tanany365 was thinking about similar issues in that PR https://github.com/jump-sdk/jetpack_compose_country_code_picker_emoji/pull/35

**Review by hbmartin — APPROVED** [review]

**Comment by hbmartin** [comment]
@omarsanchezv fyi

**Pull request merged**
